{
 "title": "AppMetricsPrometheusSample",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(api_boot_time_seconds,server)"
   },
   {
    "name": "app",
    "query": "label_values(api_boot_time_seconds,app)"
   },
   {
    "name": "env",
    "query": "label_values(api_boot_time_seconds,env)"
   }
  ]
 },
 "panels": [
  {
   "title": "运行时间",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "clocks",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - api_boot_time_seconds{server='$server',app='$app',env='$env'}"
    }
   ]
  },
  {
   "title": "吞吐量",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "rpm",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(api_response_time_count{server='$server',app='$app',env='$env'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "错误率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(api_response_time_count{server='$server',app='$app',env='$env',status!~'^2.*'}) / sum (api_response_time_count{server='$server',app='$app',env='$env'})"
    }
   ]
  },
  {
   "title": "总平均响应时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(api_response_time_sum{server='$server',app='$app',env='$env'}) / sum(api_response_time_count{server='$server',app='$app',env='$env'})"
    }
   ]
  },
  {
   "title": "2XX 平均响应时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(api_response_time_sum{server='$server',app='$app',env='$env',status=~'^2.*'}) / sum(api_response_time_count{server='$server',app='$app',env='$env',status=~'^2.*'})"
    }
   ]
  },
  {
   "title": "4XX 平均响应时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(api_response_time_sum{server='$server',app='$app',env='$env',status=~'^4.*'}) / sum(api_response_time_count{server='$server',app='$app',env='$env',status=~'^4.*'})"
    }
   ]
  },
  {
   "title": "5XX 平均响应时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(api_response_time_sum{server='$server',app='$app',env='$env',status=~'^5.*'}) / sum(api_response_time_count{server='$server',app='$app',env='$env',status=~'^5.*'})"
    }
   ]
  },
  {
   "title": "总请求数量",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(api_response_time_count{server='$server',app='$app',env='$env'})"
    }
   ]
  },
  {
   "title": "请求数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, route)(api_response_time_count{server='$server',app='$app',env='$env'})"
    }
   ]
  },
  {
   "title": "响应状态码",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(api_response_time_count{server='$server',app='$app',env='$env'})"
    }
   ]
  },
  {
   "title": "Exception",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exception)(api_exception_count{server='$server',app='$app',env='$env'})"
    }
   ]
  },
  {
   "title": "接口95%响应时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (method, route)(api_response_time{server='$server',app='$app',env='$env',quantile=\"0.95\"})"
    }
   ]
  },
  {
   "title": "5XX 接口",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, route)(api_response_time_count{server='$server',app='$app',env='$env',status!~'2.*'})"
    }
   ]
  }
 ]
}