{
 "title": "DotNetFrameworkWebAPISample",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(api_boot_time_seconds,server)"
   },
   {
    "name": "app",
    "query": "label_values(api_boot_time_seconds,app)"
   },
   {
    "name": "env",
    "query": "label_values(api_boot_time_seconds,env)"
   }
  ]
 },
 "panels": [
  {
   "title": "运行时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "clocks",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - api_boot_time_seconds{server='$server',app='$app',env='$env'}"
    }
   ]
  },
  {
   "title": "吞吐量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "rpm",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(api_response_time_count{server='$server',app='$app',env='$env'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "总请求数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(api_response_status_code{server='$server',app='$app',env='$env'})"
    }
   ]
  },
  {
   "title": "错误率",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(api_response_status_code{server='$server',app='$app',env='$env',status_code!~'^2.*'}) / sum (api_response_status_code{server='$server',app='$app',env='$env'})"
    }
   ]
  },
  {
   "title": "平均响应时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(api_response_time_sum{server='$server',app='$app',env='$env'}) / sum(api_response_time_count{server='$server',app='$app',env='$env'})"
    }
   ]
  },
  {
   "title": "请求数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, route)(api_response_status_code{server='$server',app='$app',env='$env'})"
    }
   ]
  },
  {
   "title": "接口95%响应时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (method, route)(api_response_time{server='$server',app='$app',env='$env',quantile=\"0.95\"})"
    }
   ]
  },
  {
   "title": "响应状态码",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code)(api_response_status_code{server='$server',app='$app',env='$env'})"
    }
   ]
  }
 ]
}